# Generated by Django 5.0.1 on 2024-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechGuru', '0002_rename_sp_details_ct_allcourses_startedfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='Started from'),
        ),
    ]
