# Generated by Django 5.0.1 on 2024-01-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechGuru', '0003_alter_allcourses_startedfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedfrom',
        ),
    ]
