# Generated by Django 5.0.1 on 2024-01-10 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechGuru', '0004_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
